include:
  - board: seeeduino_xiao_ble
    shield: sync24_left
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: sync24_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
